apiVersion: v1
kind: Service
metadata:
  name: {{ include "sri-devapp-frontend.fullname" . }}
  labels:
    {{- include "sri-devapp-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http   
    #- port: {{ .Values.service.port }}
      #protocol: TCP
      #targetPort: https
      #name: https
  selector:
    {{- include "sri-devapp-frontend.selectorLabels" . | nindent 4 }}
